package com.walls.entidades;
// Generated 15-may-2020 17:52:10 by Hibernate Tools 5.4.14.Final

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private ClienteId id;

	public Cliente() {
	}

	public Cliente(ClienteId id) {
		this.id = id;
	}

	public ClienteId getId() {
		return this.id;
	}

	public void setId(ClienteId id) {
		this.id = id;
	}

}
