package com.walls.entidades;
// Generated 15-may-2020 17:52:10 by Hibernate Tools 5.4.14.Final

import java.util.Date;

/**
 * ClienteId generated by hbm2java
 */
public class ClienteId implements java.io.Serializable {

	private Integer codCliente;
	private String dni;
	private String nombre;
	private String apellido;
	private Date fechaAlta;
	private Integer codClinica;

	public ClienteId() {
	}

	public ClienteId(Integer codCliente, String dni, String nombre, String apellido, Date fechaAlta,
			Integer codClinica) {
		this.codCliente = codCliente;
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.fechaAlta = fechaAlta;
		this.codClinica = codClinica;
	}

	public Integer getCodCliente() {
		return this.codCliente;
	}

	public void setCodCliente(Integer codCliente) {
		this.codCliente = codCliente;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Integer getCodClinica() {
		return this.codClinica;
	}

	public void setCodClinica(Integer codClinica) {
		this.codClinica = codClinica;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClienteId))
			return false;
		ClienteId castOther = (ClienteId) other;

		return ((this.getCodCliente() == castOther.getCodCliente()) || (this.getCodCliente() != null
				&& castOther.getCodCliente() != null && this.getCodCliente().equals(castOther.getCodCliente())))
				&& ((this.getDni() == castOther.getDni()) || (this.getDni() != null && castOther.getDni() != null
						&& this.getDni().equals(castOther.getDni())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getApellido() == castOther.getApellido()) || (this.getApellido() != null
						&& castOther.getApellido() != null && this.getApellido().equals(castOther.getApellido())))
				&& ((this.getFechaAlta() == castOther.getFechaAlta()) || (this.getFechaAlta() != null
						&& castOther.getFechaAlta() != null && this.getFechaAlta().equals(castOther.getFechaAlta())))
				&& ((this.getCodClinica() == castOther.getCodClinica())
						|| (this.getCodClinica() != null && castOther.getCodClinica() != null
								&& this.getCodClinica().equals(castOther.getCodClinica())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodCliente() == null ? 0 : this.getCodCliente().hashCode());
		result = 37 * result + (getDni() == null ? 0 : this.getDni().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getApellido() == null ? 0 : this.getApellido().hashCode());
		result = 37 * result + (getFechaAlta() == null ? 0 : this.getFechaAlta().hashCode());
		result = 37 * result + (getCodClinica() == null ? 0 : this.getCodClinica().hashCode());
		return result;
	}

}
