package com.walls.entidades;
// Generated 15-may-2020 17:52:10 by Hibernate Tools 5.4.14.Final

/**
 * Clinica generated by hbm2java
 */
public class Clinica implements java.io.Serializable {

	private ClinicaId id;

	public Clinica() {
	}

	public Clinica(ClinicaId id) {
		this.id = id;
	}

	public ClinicaId getId() {
		return this.id;
	}

	public void setId(ClinicaId id) {
		this.id = id;
	}

}
