package com.walls.entidades;
// Generated 15-may-2020 17:52:10 by Hibernate Tools 5.4.14.Final

/**
 * MascotaId generated by hbm2java
 */
public class MascotaId implements java.io.Serializable {

	private Integer codMascota;
	private String nombre;
	private String tipo;
	private String raza;
	private Integer codCliente;

	public MascotaId() {
	}

	public MascotaId(Integer codMascota, String nombre, String tipo, String raza, Integer codCliente) {
		this.codMascota = codMascota;
		this.nombre = nombre;
		this.tipo = tipo;
		this.raza = raza;
		this.codCliente = codCliente;
	}

	public Integer getCodMascota() {
		return this.codMascota;
	}

	public void setCodMascota(Integer codMascota) {
		this.codMascota = codMascota;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getRaza() {
		return this.raza;
	}

	public void setRaza(String raza) {
		this.raza = raza;
	}

	public Integer getCodCliente() {
		return this.codCliente;
	}

	public void setCodCliente(Integer codCliente) {
		this.codCliente = codCliente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MascotaId))
			return false;
		MascotaId castOther = (MascotaId) other;

		return ((this.getCodMascota() == castOther.getCodMascota()) || (this.getCodMascota() != null
				&& castOther.getCodMascota() != null && this.getCodMascota().equals(castOther.getCodMascota())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null && castOther.getTipo() != null
						&& this.getTipo().equals(castOther.getTipo())))
				&& ((this.getRaza() == castOther.getRaza()) || (this.getRaza() != null && castOther.getRaza() != null
						&& this.getRaza().equals(castOther.getRaza())))
				&& ((this.getCodCliente() == castOther.getCodCliente())
						|| (this.getCodCliente() != null && castOther.getCodCliente() != null
								&& this.getCodCliente().equals(castOther.getCodCliente())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodMascota() == null ? 0 : this.getCodMascota().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getTipo() == null ? 0 : this.getTipo().hashCode());
		result = 37 * result + (getRaza() == null ? 0 : this.getRaza().hashCode());
		result = 37 * result + (getCodCliente() == null ? 0 : this.getCodCliente().hashCode());
		return result;
	}

}
