package com.walls.entidades;
// Generated 15-may-2020 17:52:10 by Hibernate Tools 5.4.14.Final

/**
 * Mascota generated by hbm2java
 */
public class Mascota implements java.io.Serializable {

	private MascotaId id;

	public Mascota() {
	}

	public Mascota(MascotaId id) {
		this.id = id;
	}

	public MascotaId getId() {
		return this.id;
	}

	public void setId(MascotaId id) {
		this.id = id;
	}

}
